### ISSUE TITLE
Fix template error in adjustment controller view

### ISSUE THREAD

**Issue by dkubb** [MountainRoseHerbs/spree#436]
See: https://rpm.newrelic.com/accounts/241852/applications/3010604/filterable_errors#/show/1761b361-4ddf-11e6-ac40-f8bc12425d4c_0_28909/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart&_k=4cvn7n

**Comment by mbj** [comment]
This was addressed recently.
