### ISSUE TITLE
Add Spree::MemoryScope#first!

### ISSUE THREAD

**Issue by dkubb** [MountainRoseHerbs/spree#63]
We should have a `#first!` method that behaves similarly to `ActiveRecord::Relation#first!` and raises an error if there is no object to return.

**Comment by mbj** [comment]
This enhancement is redundant with recent developments that will remove the `MemoryScope` in the mid term. The improvements that will remove the `MemoryScope` are more priorized than this feature request, hence we can close this ticket.
